// SPDX-License-Identifier: (LGPL-2.1 OR BSD-2-Clause)
//
// THIS FILE IS AUTOGENERATED BY CARGO-LIBBPF-GEN!

pub use self::imp::*;

#[allow(dead_code)]
#[allow(non_snake_case)]
#[allow(non_camel_case_types)]
#[allow(clippy::absolute_paths)]
#[allow(clippy::transmute_ptr_to_ref)]
#[allow(clippy::upper_case_acronyms)]
#[warn(single_use_lifetimes)]
mod imp {
    #[allow(unused_imports)]
    use super::*;
    use libbpf_rs::libbpf_sys;
    use libbpf_rs::skel::OpenSkel;
    use libbpf_rs::skel::Skel;
    use libbpf_rs::skel::SkelBuilder;

    fn build_skel_config(
    ) -> libbpf_rs::Result<libbpf_rs::__internal_skel::ObjectSkeletonConfig<'static>> {
        let mut builder = libbpf_rs::__internal_skel::ObjectSkeletonConfigBuilder::new(DATA);
        builder
            .name("openat_bpf")
            .map("ringbuf", false)
            .map("openat_b.rodata", false)
            .prog("detect_openat");

        builder.build()
    }

    #[derive(Default)]
    pub struct OpenatSkelBuilder {
        pub obj_builder: libbpf_rs::ObjectBuilder,
    }

    impl<'a> SkelBuilder<'a> for OpenatSkelBuilder {
        type Output = OpenOpenatSkel<'a>;
        fn open(self) -> libbpf_rs::Result<OpenOpenatSkel<'a>> {
            let opts = *self.obj_builder.opts();
            self.open_opts(opts)
        }

        fn open_opts(
            self,
            open_opts: libbpf_sys::bpf_object_open_opts,
        ) -> libbpf_rs::Result<OpenOpenatSkel<'a>> {
            let mut skel_config = build_skel_config()?;

            let ret =
                unsafe { libbpf_sys::bpf_object__open_skeleton(skel_config.get(), &open_opts) };
            if ret != 0 {
                return Err(libbpf_rs::Error::from_raw_os_error(-ret));
            }

            let obj = unsafe { libbpf_rs::OpenObject::from_ptr(skel_config.object_ptr())? };

            #[allow(unused_mut)]
            let mut skel = OpenOpenatSkel {
                obj,
                // SAFETY: Our `struct_ops` type contains only pointers,
                //         which are allowed to be NULL.
                // TODO: Generate and use a `Default` representation
                //       instead, to cut down on unsafe code.
                struct_ops: unsafe { std::mem::zeroed() },
                skel_config,
            };

            Ok(skel)
        }

        fn object_builder(&self) -> &libbpf_rs::ObjectBuilder {
            &self.obj_builder
        }
        fn object_builder_mut(&mut self) -> &mut libbpf_rs::ObjectBuilder {
            &mut self.obj_builder
        }
    }

    pub struct OpenOpenatMapsMut<'a> {
        inner: &'a mut libbpf_rs::OpenObject,
    }

    impl OpenOpenatMapsMut<'_> {
        pub fn ringbuf(&mut self) -> &mut libbpf_rs::OpenMap {
            self.inner.map_mut("ringbuf").unwrap()
        }

        pub fn rodata(&mut self) -> &mut libbpf_rs::OpenMap {
            self.inner.map_mut("openat_b.rodata").unwrap()
        }
    }

    pub struct OpenOpenatMaps<'a> {
        inner: &'a libbpf_rs::OpenObject,
    }

    impl OpenOpenatMaps<'_> {
        pub fn ringbuf(&self) -> &libbpf_rs::OpenMap {
            self.inner.map("ringbuf").unwrap()
        }

        pub fn rodata(&self) -> &libbpf_rs::OpenMap {
            self.inner.map("openat_b.rodata").unwrap()
        }
    }

    pub struct OpenOpenatProgs<'a> {
        inner: &'a libbpf_rs::OpenObject,
    }

    impl OpenOpenatProgs<'_> {
        pub fn detect_openat(&self) -> &libbpf_rs::OpenProgram {
            self.inner.prog("detect_openat").unwrap()
        }
    }

    pub struct OpenOpenatProgsMut<'a> {
        inner: &'a mut libbpf_rs::OpenObject,
    }

    impl OpenOpenatProgsMut<'_> {
        pub fn detect_openat(&mut self) -> &mut libbpf_rs::OpenProgram {
            self.inner.prog_mut("detect_openat").unwrap()
        }
    }

    pub mod openat_types {
        #[allow(unused_imports)]
        use super::*;
        #[derive(Debug, Copy, Clone)]
        #[repr(C)]
        pub struct rodata {}

        #[derive(Debug, Clone)]
        #[repr(C)]
        pub struct struct_ops {}

        impl struct_ops {}
    }

    pub struct OpenOpenatSkel<'a> {
        pub obj: libbpf_rs::OpenObject,
        pub struct_ops: openat_types::struct_ops,
        skel_config: libbpf_rs::__internal_skel::ObjectSkeletonConfig<'a>,
    }

    impl<'a> OpenSkel for OpenOpenatSkel<'a> {
        type Output = OpenatSkel<'a>;
        fn load(mut self) -> libbpf_rs::Result<OpenatSkel<'a>> {
            let ret = unsafe { libbpf_sys::bpf_object__load_skeleton(self.skel_config.get()) };
            if ret != 0 {
                return Err(libbpf_rs::Error::from_raw_os_error(-ret));
            }

            let obj = unsafe { libbpf_rs::Object::from_ptr(self.obj.take_ptr())? };

            Ok(OpenatSkel {
                obj,
                struct_ops: self.struct_ops,
                skel_config: self.skel_config,
                links: OpenatLinks::default(),
            })
        }

        fn open_object(&self) -> &libbpf_rs::OpenObject {
            &self.obj
        }

        fn open_object_mut(&mut self) -> &mut libbpf_rs::OpenObject {
            &mut self.obj
        }
    }
    impl OpenOpenatSkel<'_> {
        pub fn progs_mut(&mut self) -> OpenOpenatProgsMut<'_> {
            OpenOpenatProgsMut {
                inner: &mut self.obj,
            }
        }

        pub fn progs(&self) -> OpenOpenatProgs<'_> {
            OpenOpenatProgs { inner: &self.obj }
        }

        pub fn maps_mut(&mut self) -> OpenOpenatMapsMut<'_> {
            OpenOpenatMapsMut {
                inner: &mut self.obj,
            }
        }

        pub fn maps(&self) -> OpenOpenatMaps<'_> {
            OpenOpenatMaps { inner: &self.obj }
        }
    }

    pub struct OpenatMapsMut<'a> {
        inner: &'a mut libbpf_rs::Object,
    }

    impl OpenatMapsMut<'_> {
        pub fn ringbuf(&mut self) -> &mut libbpf_rs::Map {
            self.inner.map_mut("ringbuf").unwrap()
        }

        pub fn rodata(&mut self) -> &mut libbpf_rs::Map {
            self.inner.map_mut("openat_b.rodata").unwrap()
        }
    }

    pub struct OpenatMaps<'a> {
        inner: &'a libbpf_rs::Object,
    }

    impl OpenatMaps<'_> {
        pub fn ringbuf(&self) -> &libbpf_rs::Map {
            self.inner.map("ringbuf").unwrap()
        }

        pub fn rodata(&self) -> &libbpf_rs::Map {
            self.inner.map("openat_b.rodata").unwrap()
        }
    }

    pub struct OpenatProgs<'a> {
        inner: &'a libbpf_rs::Object,
    }

    impl OpenatProgs<'_> {
        pub fn detect_openat(&self) -> &libbpf_rs::Program {
            self.inner.prog("detect_openat").unwrap()
        }
    }

    pub struct OpenatProgsMut<'a> {
        inner: &'a mut libbpf_rs::Object,
    }

    impl OpenatProgsMut<'_> {
        pub fn detect_openat(&mut self) -> &mut libbpf_rs::Program {
            self.inner.prog_mut("detect_openat").unwrap()
        }
    }

    #[derive(Default)]
    pub struct OpenatLinks {
        pub detect_openat: Option<libbpf_rs::Link>,
    }

    pub struct OpenatSkel<'a> {
        pub obj: libbpf_rs::Object,
        struct_ops: openat_types::struct_ops,
        skel_config: libbpf_rs::__internal_skel::ObjectSkeletonConfig<'a>,
        pub links: OpenatLinks,
    }

    unsafe impl Send for OpenatSkel<'_> {}
    unsafe impl Sync for OpenatSkel<'_> {}

    impl Skel for OpenatSkel<'_> {
        fn object(&self) -> &libbpf_rs::Object {
            &self.obj
        }

        fn object_mut(&mut self) -> &mut libbpf_rs::Object {
            &mut self.obj
        }

        fn attach(&mut self) -> libbpf_rs::Result<()> {
            let ret = unsafe { libbpf_sys::bpf_object__attach_skeleton(self.skel_config.get()) };
            if ret != 0 {
                return Err(libbpf_rs::Error::from_raw_os_error(-ret));
            }

            self.links = OpenatLinks {
                detect_openat: core::ptr::NonNull::new(self.skel_config.prog_link_ptr(0)?)
                    .map(|ptr| unsafe { libbpf_rs::Link::from_ptr(ptr) }),
            };

            Ok(())
        }
    }
    impl OpenatSkel<'_> {
        pub fn progs_mut(&mut self) -> OpenatProgsMut<'_> {
            OpenatProgsMut {
                inner: &mut self.obj,
            }
        }

        pub fn progs(&self) -> OpenatProgs<'_> {
            OpenatProgs { inner: &self.obj }
        }

        pub fn maps_mut(&mut self) -> OpenatMapsMut<'_> {
            OpenatMapsMut {
                inner: &mut self.obj,
            }
        }

        pub fn maps(&self) -> OpenatMaps<'_> {
            OpenatMaps { inner: &self.obj }
        }

        pub fn struct_ops_raw(&self) -> *const openat_types::struct_ops {
            &self.struct_ops
        }

        pub fn struct_ops(&self) -> &openat_types::struct_ops {
            &self.struct_ops
        }
    }

    const DATA: &[u8] = &[
        127, 69, 76, 70, 2, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 247, 0, 1, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 112, 9, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 64, 0, 0, 0, 0,
        0, 64, 0, 10, 0, 1, 0, 0, 46, 115, 116, 114, 116, 97, 98, 0, 46, 115, 121, 109, 116, 97,
        98, 0, 116, 112, 47, 115, 121, 115, 99, 97, 108, 108, 115, 47, 115, 121, 115, 95, 101, 110,
        116, 101, 114, 95, 111, 112, 101, 110, 97, 116, 0, 46, 109, 97, 112, 115, 0, 46, 114, 111,
        100, 97, 116, 97, 0, 108, 105, 99, 101, 110, 115, 101, 0, 111, 112, 101, 110, 97, 116, 46,
        98, 112, 102, 46, 99, 0, 76, 66, 66, 48, 95, 50, 0, 100, 101, 116, 101, 99, 116, 95, 111,
        112, 101, 110, 97, 116, 46, 95, 95, 95, 95, 102, 109, 116, 0, 76, 66, 66, 48, 95, 51, 0,
        100, 101, 116, 101, 99, 116, 95, 111, 112, 101, 110, 97, 116, 0, 114, 105, 110, 103, 98,
        117, 102, 0, 95, 108, 105, 99, 101, 110, 115, 101, 0, 46, 114, 101, 108, 116, 112, 47, 115,
        121, 115, 99, 97, 108, 108, 115, 47, 115, 121, 115, 95, 101, 110, 116, 101, 114, 95, 111,
        112, 101, 110, 97, 116, 0, 46, 66, 84, 70, 0, 46, 66, 84, 70, 46, 101, 120, 116, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 68, 0, 0,
        0, 4, 0, 241, 255, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 3, 0, 3, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 81, 0, 0, 0, 0, 0, 3, 0, 136, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 88, 0, 0, 0, 1, 0, 5, 0, 0, 0, 0, 0, 0, 0, 0, 0, 29, 0, 0,
        0, 0, 0, 0, 0, 110, 0, 0, 0, 0, 0, 3, 0, 248, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 3, 0, 5, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 117, 0, 0, 0, 18,
        0, 3, 0, 0, 0, 0, 0, 0, 0, 0, 0, 8, 1, 0, 0, 0, 0, 0, 0, 131, 0, 0, 0, 17, 0, 4, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 16, 0, 0, 0, 0, 0, 0, 0, 139, 0, 0, 0, 17, 0, 6, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 4, 0, 0, 0, 0, 0, 0, 0, 191, 24, 0, 0, 0, 0, 0, 0, 133, 0, 0, 0, 14, 0, 0, 0, 191, 9, 0,
        0, 0, 0, 0, 0, 183, 6, 0, 0, 0, 0, 0, 0, 24, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        183, 2, 0, 0, 20, 2, 0, 0, 183, 3, 0, 0, 0, 0, 0, 0, 133, 0, 0, 0, 131, 0, 0, 0, 191, 7, 0,
        0, 0, 0, 0, 0, 85, 7, 6, 0, 0, 0, 0, 0, 24, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        183, 2, 0, 0, 29, 0, 0, 0, 133, 0, 0, 0, 6, 0, 0, 0, 183, 6, 0, 0, 1, 0, 0, 0, 5, 0, 14, 0,
        0, 0, 0, 0, 119, 9, 0, 0, 32, 0, 0, 0, 99, 151, 0, 0, 0, 0, 0, 0, 121, 131, 24, 0, 0, 0, 0,
        0, 191, 113, 0, 0, 0, 0, 0, 0, 7, 1, 0, 0, 20, 0, 0, 0, 183, 2, 0, 0, 0, 2, 0, 0, 133, 0,
        0, 0, 114, 0, 0, 0, 191, 113, 0, 0, 0, 0, 0, 0, 7, 1, 0, 0, 4, 0, 0, 0, 183, 2, 0, 0, 16,
        0, 0, 0, 133, 0, 0, 0, 16, 0, 0, 0, 191, 113, 0, 0, 0, 0, 0, 0, 183, 2, 0, 0, 0, 0, 0, 0,
        133, 0, 0, 0, 132, 0, 0, 0, 191, 96, 0, 0, 0, 0, 0, 0, 149, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 98, 112, 102, 95, 114, 105, 110, 103, 98, 117, 102,
        95, 114, 101, 115, 101, 114, 118, 101, 32, 102, 97, 105, 108, 101, 100, 92, 110, 0, 71, 80,
        76, 0, 0, 0, 0, 0, 0, 0, 0, 32, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 8, 0, 0, 0, 88, 0, 0, 0,
        0, 0, 0, 0, 1, 0, 0, 0, 6, 0, 0, 0, 159, 235, 1, 0, 24, 0, 0, 0, 0, 0, 0, 0, 252, 1, 0, 0,
        252, 1, 0, 0, 227, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 3, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 4,
        0, 0, 0, 32, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 3, 0, 0, 0, 0, 2, 0, 0, 0, 4, 0, 0, 0, 27, 0, 0,
        0, 5, 0, 0, 0, 0, 0, 0, 1, 4, 0, 0, 0, 32, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 6, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 3, 0, 0, 0, 0, 2, 0, 0, 0, 4, 0, 0, 0, 0, 0, 4, 0, 0, 0, 0, 0, 2, 0, 0,
        4, 16, 0, 0, 0, 25, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 30, 0, 0, 0, 5, 0, 0, 0, 64, 0, 0, 0,
        42, 0, 0, 0, 0, 0, 0, 14, 7, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 10, 0, 0, 0, 50,
        0, 0, 0, 6, 0, 0, 4, 48, 0, 0, 0, 72, 0, 0, 0, 11, 0, 0, 0, 0, 0, 0, 0, 79, 0, 0, 0, 12, 0,
        0, 0, 64, 0, 0, 0, 90, 0, 0, 0, 12, 0, 0, 0, 128, 0, 0, 0, 94, 0, 0, 0, 13, 0, 0, 0, 192,
        0, 0, 0, 103, 0, 0, 0, 12, 0, 0, 0, 0, 1, 0, 0, 109, 0, 0, 0, 12, 0, 0, 0, 64, 1, 0, 0,
        114, 0, 0, 0, 0, 0, 0, 1, 8, 0, 0, 0, 64, 0, 0, 0, 133, 0, 0, 0, 0, 0, 0, 1, 8, 0, 0, 0,
        64, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 2, 14, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 10, 15, 0, 0, 0,
        138, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 8, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 13, 2, 0, 0, 0, 143,
        0, 0, 0, 9, 0, 0, 0, 147, 0, 0, 0, 1, 0, 0, 12, 16, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 3, 0, 0,
        0, 0, 14, 0, 0, 0, 4, 0, 0, 0, 29, 0, 0, 0, 161, 0, 0, 0, 0, 0, 0, 14, 18, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 3, 0, 0, 0, 0, 15, 0, 0, 0, 4, 0, 0, 0, 4, 0, 0, 0, 183, 0, 0,
        0, 0, 0, 0, 14, 20, 0, 0, 0, 1, 0, 0, 0, 176, 2, 0, 0, 1, 0, 0, 15, 16, 0, 0, 0, 8, 0, 0,
        0, 0, 0, 0, 0, 16, 0, 0, 0, 182, 2, 0, 0, 1, 0, 0, 15, 29, 0, 0, 0, 19, 0, 0, 0, 0, 0, 0,
        0, 29, 0, 0, 0, 190, 2, 0, 0, 1, 0, 0, 15, 4, 0, 0, 0, 21, 0, 0, 0, 0, 0, 0, 0, 4, 0, 0, 0,
        0, 105, 110, 116, 0, 95, 95, 65, 82, 82, 65, 89, 95, 83, 73, 90, 69, 95, 84, 89, 80, 69,
        95, 95, 0, 116, 121, 112, 101, 0, 109, 97, 120, 95, 101, 110, 116, 114, 105, 101, 115, 0,
        114, 105, 110, 103, 98, 117, 102, 0, 115, 121, 115, 95, 101, 110, 116, 101, 114, 95, 111,
        112, 101, 110, 97, 116, 95, 97, 114, 103, 115, 0, 117, 110, 117, 115, 101, 100, 0, 115,
        121, 115, 99, 97, 108, 108, 95, 110, 114, 0, 100, 102, 100, 0, 102, 105, 108, 101, 110, 97,
        109, 101, 0, 102, 108, 97, 103, 115, 0, 109, 111, 100, 101, 0, 117, 110, 115, 105, 103,
        110, 101, 100, 32, 108, 111, 110, 103, 32, 108, 111, 110, 103, 0, 108, 111, 110, 103, 0,
        99, 104, 97, 114, 0, 99, 116, 120, 0, 100, 101, 116, 101, 99, 116, 95, 111, 112, 101, 110,
        97, 116, 0, 100, 101, 116, 101, 99, 116, 95, 111, 112, 101, 110, 97, 116, 46, 95, 95, 95,
        95, 102, 109, 116, 0, 95, 108, 105, 99, 101, 110, 115, 101, 0, 47, 104, 111, 109, 101, 47,
        118, 101, 110, 107, 121, 47, 67, 111, 100, 101, 115, 47, 115, 105, 109, 112, 108, 101, 95,
        98, 112, 102, 47, 115, 114, 99, 47, 98, 112, 102, 47, 111, 112, 101, 110, 97, 116, 46, 98,
        112, 102, 46, 99, 0, 105, 110, 116, 32, 100, 101, 116, 101, 99, 116, 95, 111, 112, 101,
        110, 97, 116, 40, 115, 116, 114, 117, 99, 116, 32, 115, 121, 115, 95, 101, 110, 116, 101,
        114, 95, 111, 112, 101, 110, 97, 116, 95, 97, 114, 103, 115, 32, 42, 99, 116, 120, 41, 32,
        123, 0, 32, 32, 32, 32, 95, 95, 117, 51, 50, 32, 112, 105, 100, 32, 61, 32, 98, 112, 102,
        95, 103, 101, 116, 95, 99, 117, 114, 114, 101, 110, 116, 95, 112, 105, 100, 95, 116, 103,
        105, 100, 40, 41, 32, 62, 62, 32, 51, 50, 59, 0, 32, 32, 32, 32, 115, 116, 114, 117, 99,
        116, 32, 101, 118, 101, 110, 116, 42, 32, 101, 118, 116, 32, 61, 32, 98, 112, 102, 95, 114,
        105, 110, 103, 98, 117, 102, 95, 114, 101, 115, 101, 114, 118, 101, 40, 38, 114, 105, 110,
        103, 98, 117, 102, 44, 32, 115, 105, 122, 101, 111, 102, 40, 115, 116, 114, 117, 99, 116,
        32, 101, 118, 101, 110, 116, 41, 44, 32, 48, 41, 59, 0, 32, 32, 32, 32, 105, 102, 32, 40,
        33, 101, 118, 116, 41, 32, 123, 0, 32, 32, 32, 32, 32, 32, 32, 32, 98, 112, 102, 95, 112,
        114, 105, 110, 116, 107, 40, 34, 98, 112, 102, 95, 114, 105, 110, 103, 98, 117, 102, 95,
        114, 101, 115, 101, 114, 118, 101, 32, 102, 97, 105, 108, 101, 100, 92, 92, 110, 34, 41,
        59, 0, 32, 32, 32, 32, 101, 118, 116, 45, 62, 112, 105, 100, 32, 61, 32, 112, 105, 100, 59,
        0, 32, 32, 32, 32, 98, 112, 102, 95, 112, 114, 111, 98, 101, 95, 114, 101, 97, 100, 95,
        117, 115, 101, 114, 95, 115, 116, 114, 40, 101, 118, 116, 45, 62, 102, 105, 108, 101, 110,
        97, 109, 101, 44, 32, 115, 105, 122, 101, 111, 102, 40, 101, 118, 116, 45, 62, 102, 105,
        108, 101, 110, 97, 109, 101, 41, 44, 32, 99, 116, 120, 45, 62, 102, 105, 108, 101, 110, 97,
        109, 101, 41, 59, 0, 32, 32, 32, 32, 98, 112, 102, 95, 103, 101, 116, 95, 99, 117, 114,
        114, 101, 110, 116, 95, 99, 111, 109, 109, 40, 101, 118, 116, 45, 62, 99, 111, 109, 109,
        44, 32, 115, 105, 122, 101, 111, 102, 40, 101, 118, 116, 45, 62, 99, 111, 109, 109, 41, 41,
        59, 0, 32, 32, 32, 32, 98, 112, 102, 95, 114, 105, 110, 103, 98, 117, 102, 95, 115, 117,
        98, 109, 105, 116, 40, 101, 118, 116, 44, 32, 48, 41, 59, 0, 125, 0, 46, 109, 97, 112, 115,
        0, 46, 114, 111, 100, 97, 116, 97, 0, 108, 105, 99, 101, 110, 115, 101, 0, 116, 112, 47,
        115, 121, 115, 99, 97, 108, 108, 115, 47, 115, 121, 115, 95, 101, 110, 116, 101, 114, 95,
        111, 112, 101, 110, 97, 116, 0, 0, 159, 235, 1, 0, 32, 0, 0, 0, 0, 0, 0, 0, 20, 0, 0, 0,
        20, 0, 0, 0, 236, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 8, 0, 0, 0, 198, 2, 0, 0, 1, 0, 0, 0, 0,
        0, 0, 0, 17, 0, 0, 0, 16, 0, 0, 0, 198, 2, 0, 0, 14, 0, 0, 0, 0, 0, 0, 0, 192, 0, 0, 0,
        242, 0, 0, 0, 0, 108, 0, 0, 8, 0, 0, 0, 192, 0, 0, 0, 41, 1, 0, 0, 17, 116, 0, 0, 32, 0, 0,
        0, 192, 0, 0, 0, 91, 1, 0, 0, 25, 120, 0, 0, 80, 0, 0, 0, 192, 0, 0, 0, 171, 1, 0, 0, 9,
        124, 0, 0, 88, 0, 0, 0, 192, 0, 0, 0, 187, 1, 0, 0, 9, 128, 0, 0, 136, 0, 0, 0, 192, 0, 0,
        0, 41, 1, 0, 0, 44, 116, 0, 0, 144, 0, 0, 0, 192, 0, 0, 0, 240, 1, 0, 0, 14, 140, 0, 0,
        152, 0, 0, 0, 192, 0, 0, 0, 4, 2, 0, 0, 72, 144, 0, 0, 160, 0, 0, 0, 192, 0, 0, 0, 4, 2, 0,
        0, 34, 144, 0, 0, 176, 0, 0, 0, 192, 0, 0, 0, 4, 2, 0, 0, 5, 144, 0, 0, 192, 0, 0, 0, 192,
        0, 0, 0, 86, 2, 0, 0, 31, 148, 0, 0, 208, 0, 0, 0, 192, 0, 0, 0, 86, 2, 0, 0, 5, 148, 0, 0,
        224, 0, 0, 0, 192, 0, 0, 0, 142, 2, 0, 0, 5, 152, 0, 0, 248, 0, 0, 0, 192, 0, 0, 0, 174, 2,
        0, 0, 1, 160, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 3, 0, 0, 0, 32, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 64, 0, 0, 0, 0, 0, 0, 0, 195, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 9, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 8, 1, 0, 0, 0, 0, 0, 0, 240, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
        0, 0, 0, 8, 0, 0, 0, 0, 0, 0, 0, 24, 0, 0, 0, 0, 0, 0, 0, 17, 0, 0, 0, 1, 0, 0, 0, 6, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 248, 1, 0, 0, 0, 0, 0, 0, 8, 1, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 8, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 46, 0, 0, 0, 1, 0, 0,
        0, 3, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 3, 0, 0, 0, 0, 0, 0, 16, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 8, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 52, 0, 0,
        0, 1, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 16, 3, 0, 0, 0, 0, 0, 0, 29,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 60, 0, 0, 0, 1, 0, 0, 0, 3, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 45, 3, 0, 0, 0,
        0, 0, 0, 4, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 148, 0, 0, 0, 9, 0, 0, 0, 64, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        56, 3, 0, 0, 0, 0, 0, 0, 32, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 3, 0, 0, 0, 8, 0, 0, 0, 0, 0,
        0, 0, 16, 0, 0, 0, 0, 0, 0, 0, 181, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 88, 3, 0, 0, 0, 0, 0, 0, 247, 4, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        8, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 186, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 80, 8, 0, 0, 0, 0, 0, 0, 32, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 8, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    ];
}
